name: PublishToDockerhub

on:
  push:
    tags:
      - 'v*'
    #branches:
    #  - main

jobs:
  publish-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.9.0
      - name: Install Yarn Packages
        run: |
          cd webui
          yarn install
      - name: Build Webui
        run: |
          cd webui
          yarn run build
          cd ..
          sed -i "s/Vue App/KubeFileBrowser/g" static/index.html
      - name: ShortSHA
        uses: benjlevesque/short-sha@v1.2
        with:
          length: 8
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: Dockerfile
          platforms: linux/arm64,linux/amd64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v6,linux/arm/v7
          push: true
          tags: |
            xmapst/kubefilebrowser:latest
            xmapst/kubefilebrowser:${{ github.ref }}